//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class Audiosettingpanel_prefab
    {
        public const string BundleName = "AUDIOSETTINGPANEL_PREFAB";
        public const string AUDIOSETTINGPANEL = "AUDIOSETTINGPANEL";
    }
    public class Inputsetlist_prefab
    {
        public const string BundleName = "INPUTSETLIST_PREFAB";
        public const string INPUTSETLIST = "INPUTSETLIST";
    }
    public class Levelpanel_prefab
    {
        public const string BundleName = "LEVELPANEL_PREFAB";
        public const string LEVELPANEL = "LEVELPANEL";
    }
    public class Losepanel_prefab
    {
        public const string BundleName = "LOSEPANEL_PREFAB";
        public const string LOSEPANEL = "LOSEPANEL";
    }
    public class Mainpanel_prefab
    {
        public const string BundleName = "MAINPANEL_PREFAB";
        public const string MAINPANEL = "MAINPANEL";
    }
    public class Panel_start_prefab
    {
        public const string BundleName = "PANEL_START_PREFAB";
        public const string PANEL_START = "PANEL_START";
    }
    public class Settingpanel_prefab
    {
        public const string BundleName = "SETTINGPANEL_PREFAB";
        public const string SETTINGPANEL = "SETTINGPANEL";
    }
    public class Winpanel_prefab
    {
        public const string BundleName = "WINPANEL_PREFAB";
        public const string WINPANEL = "WINPANEL";
    }
}
